version: '3.9'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
    # volumes:
    #       - .:/data/db
  livraria:
    build: .
    command: "npm start"   
    container_name: livraria 
    restart: always
    networks:
      - compose-bridge
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb
networks:
  compose-bridge:
    driver: bridge